# Generated by Django 4.1.3 on 2022-11-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoManut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('nota', models.IntegerField()),
                ('subestacao', models.CharField(max_length=5)),
                ('tipo_insp', models.CharField(max_length=20)),
                ('mes', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('equipamento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.IntegerField()),
                ('data_inic', models.DateField()),
                ('hora_inic', models.TimeField()),
                ('data_fim', models.DateField()),
                ('hora_fim', models.TimeField()),
                ('tempo_desloc', models.FloatField()),
                ('tempo_trab', models.FloatField()),
                ('tempo_escrit', models.FloatField()),
                ('is_lac', models.BooleanField()),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.planomanut')),
            ],
        ),
    ]
