# Generated by Django 4.1.3 on 2022-11-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planomanut',
            old_name='subestacao',
            new_name='local_inst',
        ),
    ]
