# Generated by Django 4.1.3 on 2022-11-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_planomanut_cod_local_inst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planomanut',
            name='equipamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
